import {
  APP_FEATURES as FEATURES,
  APP_HTML_ELEMENTS as HTML_ELEMENTS,
} from '~core/constants';

/* Define specific Ids for UI elements */
export const AUTH_ID = {
  AUTH_LOGIN_FORM: `${FEATURES.AUTH}-${HTML_ELEMENTS.FORM}-login`,
  AUTH_LOGIN_PAGE: `${FEATURES.AUTH}-loginPage`,

  BUTTON_CANCEL: `${FEATURES.AUTH}-${HTML_ELEMENTS.BUTTON}-cancel`,
  BUTTON_CREATE: `${FEATURES.AUTH}-${HTML_ELEMENTS.BUTTON}-create`,
  BUTTON_LOGIN: `${FEATURES.AUTH}-${HTML_ELEMENTS.BUTTON}-login`,
  BUTTON_SUBMIT: `${FEATURES.AUTH}-${HTML_ELEMENTS.BUTTON}-submit`,

  DIALOG_PASSWORD_CHANGE: `${FEATURES.AUTH}-${HTML_ELEMENTS.DIALOG}-passwordChange`,

  TOAST_UPDATE_PASSWORD_FAILED: `${FEATURES.AUTH}-${HTML_ELEMENTS.NOTIFICATION}-updatePassword-failed`,
  TOAST_UPDATE_PASSWORD_SUCCESS: `${FEATURES.AUTH}-${HTML_ELEMENTS.NOTIFICATION}-updatePassword-success`,
};
