import {
  APP_FEATURES as FEATURES,
  APP_HTML_ELEMENTS as HTML_ELEMENTS,
} from '~core/constants';

/* Define specific Ids for UI elements */
export const CONTACT_ID = {
  BUTTON_CANCEL: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.BUTTON}-cancel`,
  BUTTON_CLOSE: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.BUTTON}-close`,
  BUTTON_CREATE: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.BUTTON}-create`,
  BUTTON_DELETE_DISABLED: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.BUTTON}-delete-disabled`,
  BUTTON_DELETE_ENABLED: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.BUTTON}-delete-enabled`,
  BUTTON_DOWNLOAD: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.BUTTON}-download`,
  BUTTON_SUBMIT: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.BUTTON}-submit`,

  CONTACT_DETAILS: `${FEATURES.CONTACTS}-details`,
  CONTACT_DETAILS_LIST: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.LIST}-details`,
  CONTACT_DIALOG: `${FEATURES.CONTACTS}-dialog`,
  CONTACT_FORM_CREATE: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.FORM}-create`,
  CONTACT_FORM_EDIT: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.FORM}-edit`,
  CONTACT_LIST: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.TABLE}-contactList`,
  CONTACT_LIST_NOT_FOUND: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.TABLE}-empty`,
  CONTACT_LIST_PAGINATION: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.PAGINATION}-contactList`,
  CONTACT_MAIN_SECTION: `${FEATURES.CONTACTS}`,

  INPUT_SEARCH: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.FORM}-search`,
  
  TOAST_ADD_FAILED: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.NOTIFICATION}-addFailed`,
  TOAST_ADD_SUCCESS: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.NOTIFICATION}-addSuccess`,
  TOAST_DELETE_FAILED: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.NOTIFICATION}-deleteFailed`,
  TOAST_DELETE_MULTIPLE_FAILED: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.NOTIFICATION}-deleteMultipleFailed`,
  TOAST_DELETE_MULTIPLE_SUCCESS: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.NOTIFICATION}-deleteMultipleSuccess`,
  TOAST_DELETE_SUCCESS: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.NOTIFICATION}-deleteSuccess`,
  TOAST_UPDATE_FAILED: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.NOTIFICATION}-updateFailed`,
  TOAST_UPDATE_SUCCESS: `${FEATURES.CONTACTS}-${HTML_ELEMENTS.NOTIFICATION}-updateSuccess`,
};
