import {
  APP_FEATURES as FEATURES,
  APP_HTML_ELEMENTS as HTML_ELEMENTS,
} from '~core/constants';

/* Define specific Ids for UI elements */
export const USER_ID = {
  BUTTON_CANCEL: `${FEATURES.USERS}-${HTML_ELEMENTS.BUTTON}-cancel`,
  BUTTON_CREATE: `${FEATURES.USERS}-${HTML_ELEMENTS.BUTTON}-create`,
  BUTTON_SUBMIT: `${FEATURES.USERS}-${HTML_ELEMENTS.BUTTON}-submit`,

  USER_DIALOG: `${FEATURES.USERS}-dialog`,
  USER_FORM_CREATE: `${FEATURES.USERS}-${HTML_ELEMENTS.FORM}-create`,
  USER_FORM_EDIT: `${FEATURES.USERS}-${HTML_ELEMENTS.FORM}-edit`,
  USER_LIST_NOT_FOUND: `${FEATURES.USERS}-${HTML_ELEMENTS.TABLE}-empty`,
  USER_LIST_PAGINATION: `${FEATURES.USERS}-${HTML_ELEMENTS.PAGINATION}-userList`,
  USER_LIST: `${FEATURES.USERS}-${HTML_ELEMENTS.TABLE}-userList`,
  USER_MAIN_SECTION: `${FEATURES.USERS}`,

  TOAST_ADD_FAILED: `${FEATURES.USERS}-${HTML_ELEMENTS.NOTIFICATION}-addFailed`,
  TOAST_ADD_SUCCESS: `${FEATURES.USERS}-${HTML_ELEMENTS.NOTIFICATION}-addSuccess`,
  TOAST_UPDATE_FAILED: `${FEATURES.USERS}-${HTML_ELEMENTS.NOTIFICATION}-updateFailed`,
  TOAST_UPDATE_SUCCESS: `${FEATURES.USERS}-${HTML_ELEMENTS.NOTIFICATION}-updateSuccess`,
};
