import {
  APP_FEATURES as FEATURES,
  APP_HTML_ELEMENTS as HTML_ELEMENTS,
} from '~core/constants';

/* Define specific Ids for UI elements */
export const SALES_ORDER_ID = {
  BUTTON_CANCEL: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.BUTTON}-cancel`,
  BUTTON_CLOSE: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.BUTTON}-close`,
  BUTTON_CREATE: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.BUTTON}-create`,
  BUTTON_DELETE_DISABLED: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.BUTTON}-delete-disabled`,
  BUTTON_DELETE_ENABLED: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.BUTTON}-delete-enabled`,
  BUTTON_SUBMIT: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.BUTTON}-submit`,

  INPUT_SEARCH: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.FORM}-search`,

  SALES_ORDER_DETAILS_LIST: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.LIST}-details`,
  SALES_ORDER_DETAILS: `${FEATURES.SALES_ORDERS}-details`,
  SALES_ORDER_DIALOG: `${FEATURES.SALES_ORDERS}-dialog`,
  SALES_ORDER_FORM_CREATE: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.FORM}-create`,
  SALES_ORDER_FORM_EDIT: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.FORM}-edit`,
  SALES_ORDER_LIST_NOT_FOUND: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.TABLE}-empty`,
  SALES_ORDER_LIST_PAGINATION: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.PAGINATION}-salesOrderList`,
  SALES_ORDER_LIST: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.TABLE}-salesOrderList`,
  SALES_ORDER_MAIN_SECTION: `${FEATURES.SALES_ORDERS}`,

  TOAST_ADD_FAILED: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.NOTIFICATION}-addFailed`,
  TOAST_ADD_SUCCESS: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.NOTIFICATION}-addSuccess`,
  TOAST_DELETE_FAILED: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.NOTIFICATION}-deleteFailed`,
  TOAST_DELETE_MULTIPLE_FAILED: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.NOTIFICATION}-deleteMultipleFailed`,
  TOAST_DELETE_MULTIPLE_SUCCESS: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.NOTIFICATION}-deleteMultipleSuccess`,
  TOAST_DELETE_SUCCESS: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.NOTIFICATION}-deleteSuccess`,
  TOAST_UPDATE_FAILED: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.NOTIFICATION}-updateFailed`,
  TOAST_UPDATE_SUCCESS: `${FEATURES.SALES_ORDERS}-${HTML_ELEMENTS.NOTIFICATION}-updateSuccess`,
};
